/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AcademicYearFeeSettings {
  academic_year_id: number;
  default_fee_plan_id: number;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface AcademicYears {
  created_at: Generated<Date>;
  current_flag: Generated<number | null>;
  end_date: Date;
  id: Generated<number>;
  is_current: Generated<number>;
  name: string;
  start_date: Date;
  status: Generated<"active" | "closed" | "planned">;
  updated_at: Generated<Date>;
}

export interface Announcements {
  audience: string;
  body_html: string;
  created_at: Generated<Date>;
  created_by: number;
  expire_at: Generated<Date | null>;
  id: Generated<number>;
  is_public: Generated<number>;
  publish_at: Generated<Date | null>;
  status: Generated<"archived" | "draft" | "published" | "scheduled">;
  title: string;
  updated_at: Generated<Date>;
}

export interface AttendanceDays {
  academic_year_id: number;
  att_date: Date;
  marked_at: Generated<Date>;
  marked_by: number;
  section_id: number;
  updated_at: Generated<Date | null>;
  updated_by: Generated<number | null>;
}

export interface AuditLogs {
  acting_user_id: Generated<number | null>;
  action: string;
  after_data: Generated<string | null>;
  before_data: Generated<string | null>;
  created_at: Generated<Date>;
  entity_id: Generated<number | null>;
  entity_type: Generated<string | null>;
  id: Generated<number>;
  ip_address: Generated<string | null>;
  module_key: string;
  user_agent: Generated<string | null>;
  user_id: Generated<number | null>;
  workspace: "developer" | "parent" | "staff" | "student" | "system";
}

export interface BellGroupClasses {
  academic_year_id: number;
  bell_group_id: number;
  class_id: number;
}

export interface BellGroups {
  academic_year_id: number;
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
}

export interface BellPeriods {
  bell_group_id: number;
  end_time: string;
  id: Generated<number>;
  kind: Generated<"assembly" | "break" | "lunch" | "period">;
  label: string;
  seq: number;
  start_time: string;
}

export interface BusRoutes {
  description: Generated<string | null>;
  id: Generated<number>;
  is_active: Generated<number>;
  name: string;
  vehicle_id: Generated<number | null>;
}

export interface Classes {
  created_at: Generated<Date>;
  id: Generated<number>;
  is_active: Generated<number>;
  level_order: number;
  name: string;
  updated_at: Generated<Date>;
}

export interface ClassExamSettings {
  academic_year_id: number;
  assessment: Generated<"marks" | "skills">;
  class_id: number;
  display: Generated<"both" | "grades" | "marks">;
  fa_weight: Generated<number>;
  formula: Generated<"term" | "weights" | "year_end">;
  grade_scale_id: Generated<number | null>;
  pass_pct: Generated<Decimal>;
}

export interface ClassOneTimeFees {
  academic_year_id: number;
  amount: Decimal;
  class_id: number;
  created_at: Generated<Date>;
  created_by: number;
  due_date: Generated<Date | null>;
  id: Generated<number>;
  one_time_fee_type_id: number;
  title: string;
}

export interface ClassSubjects {
  academic_year_id: number;
  class_id: number;
  display_order: Generated<number>;
  subject_id: number;
}

export interface ClassTeachers {
  academic_year_id: number;
  section_id: number;
  staff_id: number;
}

export interface ClassTuitionFees {
  academic_year_id: number;
  amount: Decimal;
  class_id: number;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface CmsAlbums {
  cover_file_id: Generated<number | null>;
  created_at: Generated<Date>;
  event_id: Generated<number | null>;
  id: Generated<number>;
  is_published: Generated<number>;
  slug: string;
  title: string;
}

export interface CmsEvents {
  cover_file_id: Generated<number | null>;
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  description: Generated<string | null>;
  end_date: Generated<Date | null>;
  event_date: Date;
  id: Generated<number>;
  is_published: Generated<number>;
  location: Generated<string | null>;
  slug: string;
  title: string;
  updated_at: Generated<Date>;
}

export interface CmsHomeSections {
  content: string;
  is_visible: Generated<number>;
  position: number;
  section_key: string;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface CmsMenuItems {
  id: Generated<number>;
  is_visible: Generated<number>;
  label: string;
  link_type: "builtin" | "page" | "url";
  location: "footer" | "header";
  new_tab: Generated<number>;
  position: Generated<number>;
  target: string;
}

export interface CmsPages {
  body: Generated<string | null>;
  id: Generated<number>;
  is_published: Generated<number>;
  kind: Generated<"about" | "contact" | "custom" | "home" | "privacy">;
  seo_description: Generated<string | null>;
  seo_title: Generated<string | null>;
  slug: string;
  title: string;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface CmsPhotos {
  album_id: number;
  caption: Generated<string | null>;
  file_id: number;
  id: Generated<number>;
  position: Generated<number>;
}

export interface CmsVideos {
  created_at: Generated<Date>;
  description: Generated<string | null>;
  event_id: Generated<number | null>;
  id: Generated<number>;
  is_published: Generated<number>;
  title: string;
  youtube_id: string;
}

export interface CoAreas {
  academic_year_id: number;
  class_id: Generated<number | null>;
  created_by: Generated<number | null>;
  id: Generated<number>;
  name: string;
  position: Generated<number>;
}

export interface CoGrades {
  area_id: number;
  grade: string;
  student_id: number;
  term: number;
  updated_by: Generated<number | null>;
}

export interface ConcessionTypes {
  id: Generated<number>;
  is_active: Generated<number>;
  name: string;
}

export interface ContactMessages {
  created_at: Generated<Date>;
  id: Generated<number>;
  ip_address: Generated<string | null>;
  message: string;
  mobile: Generated<string | null>;
  name: string;
  status: Generated<"archived" | "new" | "read">;
  user_agent: Generated<string | null>;
}

export interface CredentialIssues {
  channel: "copy" | "email" | "whatsapp_manual";
  created_at: Generated<Date>;
  id: Generated<number>;
  issued_by: number;
  user_id: number;
}

export interface EmailOutbox {
  attempts: Generated<number>;
  body_html: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  last_error: Generated<string | null>;
  sent_at: Generated<Date | null>;
  status: Generated<"failed" | "queued" | "sent">;
  subject: string;
  template_key: Generated<string | null>;
  to_email: string;
}

export interface EmailTemplates {
  body_html: string;
  is_active: Generated<number>;
  subject: string;
  template_key: string;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface Enrollments {
  academic_year_id: number;
  class_id: number;
  created_at: Generated<Date>;
  id: Generated<number>;
  joined_on: Generated<Date | null>;
  remarks: Generated<string | null>;
  roll_no: Generated<string | null>;
  section_id: number;
  status: Generated<"completed" | "detained" | "enrolled" | "left" | "promoted" | "transferred">;
  student_id: number;
  updated_at: Generated<Date>;
}

export interface ExamClasses {
  class_id: number;
  exam_id: number;
}

export interface ExamPublications {
  exam_id: number;
  published_at: Generated<Date>;
  published_by: number;
  section_id: number;
}

export interface Exams {
  academic_year_id: number;
  code: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  kind: "fa" | "prefinal" | "sa" | "unit";
  max_marks: Decimal;
  name: string;
  on_report_card: Generated<number>;
  position: Generated<number>;
  term: Generated<number | null>;
}

export interface ExamSchedule {
  class_id: number;
  end_time: Generated<string | null>;
  exam_date: Date;
  exam_id: number;
  start_time: Generated<string | null>;
  subject_id: number;
}

export interface ExpenseCategories {
  id: Generated<number>;
  is_active: Generated<number>;
  is_system: Generated<number>;
  name: string;
  sort_order: Generated<number>;
}

export interface Expenses {
  academic_year_id: number;
  amount: Decimal;
  bill_file_id: Generated<number | null>;
  category_id: number;
  created_at: Generated<Date>;
  created_by: number;
  decided_at: Generated<Date | null>;
  decided_by: Generated<number | null>;
  decision_note: Generated<string | null>;
  description: Generated<string | null>;
  expense_date: Date;
  id: Generated<number>;
  method: "bank_transfer" | "card" | "cash" | "cheque" | "upi";
  paid_to: string;
  public_id: string;
  reference_no: Generated<string | null>;
  source: Generated<"inventory" | "manual" | "payroll" | "transport">;
  status: "approved" | "cancelled" | "pending" | "rejected";
  voucher_no: string;
}

export interface Families {
  address: Generated<string | null>;
  alt_mobile: Generated<string | null>;
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  custom_data: Generated<string | null>;
  email: Generated<string | null>;
  family_name: string;
  father_name: Generated<string | null>;
  guardian_name: Generated<string | null>;
  id: Generated<number>;
  mother_name: Generated<string | null>;
  primary_mobile: string;
  public_id: string;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
  user_id: Generated<number | null>;
}

export interface FeatureFlags {
  is_enabled: Generated<number>;
  module_key: string;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface FeeItems {
  academic_year_id: number;
  amount: Decimal;
  balance: Generated<Decimal | null>;
  category: "bus" | "one_time" | "tuition";
  class_one_time_fee_id: Generated<number | null>;
  created_at: Generated<Date>;
  due_date: Generated<Date | null>;
  id: Generated<number>;
  installment_no: Generated<number | null>;
  label: string;
  paid_amount: Generated<Decimal>;
  student_fee_account_id: number;
  student_id: number;
  updated_at: Generated<Date>;
  waived_amount: Generated<Decimal>;
}

export interface FeePlans {
  id: Generated<number>;
  installment_count: number;
  name: string;
  plan_key: "half_yearly" | "quarterly" | "yearly";
}

export interface FeeReminderLog {
  amount: Decimal;
  created_at: Generated<Date>;
  due_date: Generated<Date | null>;
  id: Generated<number>;
  kind: "before_due" | "manual" | "overdue";
  sent_by: Generated<number | null>;
  sent_on: Date;
  student_id: number;
  to_email: string;
}

export interface FeeWaiverItems {
  amount: Decimal;
  fee_item_id: number;
  waiver_id: number;
}

export interface FeeWaivers {
  academic_year_id: number;
  amount: Decimal;
  created_at: Generated<Date>;
  created_by: number;
  id: Generated<number>;
  reason: string;
  student_id: number;
}

export interface FieldPolicies {
  access: "edit" | "hidden" | "view";
  entity: string;
  field_key: string;
  role_id: number;
}

export interface Files {
  created_at: Generated<Date>;
  deleted_at: Generated<Date | null>;
  disk: "local" | "s3";
  entity_id: Generated<number | null>;
  entity_type: Generated<string | null>;
  id: Generated<number>;
  mime_type: string;
  module_key: Generated<string | null>;
  original_name: string;
  public_id: string;
  size_bytes: number;
  storage_path: string;
  uploaded_by: Generated<number | null>;
  visibility: Generated<"private" | "public">;
}

export interface GradeBands {
  grade: string;
  id: Generated<number>;
  label: Generated<string | null>;
  min_pct: Decimal;
  scale_id: number;
}

export interface GradeScales {
  id: Generated<number>;
  name: string;
}

export interface Holidays {
  academic_year_id: number;
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  end_date: Date;
  id: Generated<number>;
  name: string;
  start_date: Date;
}

export interface ImportJobs {
  completed_at: Generated<Date | null>;
  created_at: Generated<Date>;
  created_by: number;
  error_rows: Generated<number>;
  errors: Generated<string | null>;
  file_id: number;
  id: Generated<number>;
  import_type: "attendance" | "families_students" | "opening_fees" | "staff";
  status: Generated<"completed" | "failed" | "importing" | "invalid" | "ready" | "uploaded" | "validating">;
  total_rows: Generated<number>;
  valid_rows: Generated<number>;
}

export interface InstitutionSettings {
  address: Generated<string | null>;
  brand_primary: Generated<string | null>;
  brand_secondary: Generated<string | null>;
  college_login_holder: Generated<"parent" | "student">;
  contact_email: Generated<string | null>;
  contact_whatsapp: Generated<string | null>;
  currency: Generated<string>;
  favicon_file_id: Generated<number | null>;
  id: Generated<number>;
  institution_type: Generated<"college" | "school">;
  logo_file_id: Generated<number | null>;
  name: string;
  phone: Generated<string | null>;
  short_name: Generated<string | null>;
  smtp_config: Generated<string | null>;
  timezone: Generated<string>;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
  website_url: Generated<string | null>;
}

export interface InventoryItems {
  category: string;
  id: Generated<number>;
  is_active: Generated<number>;
  low_stock_at: Generated<Decimal | null>;
  name: string;
  sale_price: Generated<Decimal | null>;
  stock_qty: Generated<Decimal>;
  track_stock: Generated<number>;
  unit: Generated<string>;
}

export interface ItemSetLines {
  item_id: number;
  qty: Decimal;
  set_id: number;
}

export interface ItemSets {
  class_id: Generated<number | null>;
  id: Generated<number>;
  is_active: Generated<number>;
  name: string;
  price: Decimal;
}

export interface LeaveRequests {
  created_at: Generated<Date>;
  decided_at: Generated<Date | null>;
  decided_by: Generated<number | null>;
  decision_note: Generated<string | null>;
  end_date: Date;
  id: Generated<number>;
  kind: "staff" | "student";
  leave_type_id: Generated<number | null>;
  reason: string;
  requested_by: number;
  staff_id: Generated<number | null>;
  start_date: Date;
  status: Generated<"approved" | "cancelled" | "pending" | "rejected">;
  student_id: Generated<number | null>;
}

export interface LeaveTypes {
  code: string;
  days_per_year: Generated<Decimal | null>;
  id: Generated<number>;
  is_active: Generated<number>;
  is_paid: Generated<number>;
  name: string;
  sort_order: Generated<number>;
}

export interface LoginLogs {
  created_at: Generated<Date>;
  id: Generated<number>;
  identifier: string;
  ip_address: Generated<string | null>;
  reason: Generated<string | null>;
  success: number;
  user_agent: Generated<string | null>;
  user_id: Generated<number | null>;
}

export interface MarkCorrections {
  created_at: Generated<Date>;
  decided_at: Generated<Date | null>;
  decided_by: Generated<number | null>;
  decision_note: Generated<string | null>;
  id: Generated<number>;
  mark_id: number;
  new_absent: number;
  new_marks: Generated<Decimal | null>;
  old_absent: number;
  old_marks: Generated<Decimal | null>;
  reason: string;
  requested_by: number;
  status: Generated<"approved" | "pending" | "rejected">;
}

export interface Marks {
  exam_id: number;
  id: Generated<number>;
  is_absent: Generated<number>;
  marks: Generated<Decimal | null>;
  section_id: number;
  student_id: number;
  subject_id: number;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface MarkSheets {
  approved_at: Generated<Date | null>;
  approved_by: Generated<number | null>;
  exam_id: number;
  return_note: Generated<string | null>;
  section_id: number;
  status: Generated<"approved" | "draft" | "returned" | "submitted">;
  subject_id: number;
  submitted_at: Generated<Date | null>;
  submitted_by: Generated<number | null>;
}

export interface Notifications {
  body: Generated<string | null>;
  category: "academic" | "communication" | "finance" | "system";
  created_at: Generated<Date>;
  id: Generated<number>;
  link_path: Generated<string | null>;
  read_at: Generated<Date | null>;
  title: string;
  user_id: number;
  workspace: "parent" | "staff" | "student";
}

export interface NumberSequences {
  id: Generated<number>;
  next_value: Generated<number>;
  pad_length: Generated<number>;
  prefix: Generated<string>;
  scope_key: Generated<string>;
  seq_key: string;
}

export interface OneTimeFeeTypes {
  id: Generated<number>;
  is_active: Generated<number>;
  name: string;
}

export interface PasswordResetTokens {
  created_at: Generated<Date>;
  expires_at: Date;
  id: Generated<number>;
  token_hash: string;
  used_at: Generated<Date | null>;
  user_id: number;
}

export interface PayComponents {
  calc: Generated<"fixed" | "pct_basic" | "pct_gross">;
  code: string;
  default_value: Generated<Decimal>;
  id: Generated<number>;
  is_active: Generated<number>;
  is_basic: Generated<number>;
  kind: "deduction" | "earning" | "employer";
  max_amount: Generated<Decimal | null>;
  name: string;
  prorate: Generated<number>;
  sort_order: Generated<number>;
}

export interface PaymentAllocations {
  amount: Decimal;
  fee_item_id: number;
  id: Generated<number>;
  payment_id: number;
}

export interface Payments {
  academic_year_id: number;
  balance_after: Generated<Decimal>;
  collected_by: number;
  created_at: Generated<Date>;
  id: Generated<number>;
  line_items: string;
  method: "bank_transfer" | "card" | "cash" | "cheque" | "upi";
  payment_date: Date;
  public_id: string;
  receipt_no: string;
  receipt_type: Generated<"opening_balance" | "regular">;
  reference_no: Generated<string | null>;
  remarks: Generated<string | null>;
  status: Generated<"valid" | "void">;
  student_id: number;
  total_amount: Decimal;
  void_reason: Generated<string | null>;
  voided_at: Generated<Date | null>;
  voided_by: Generated<number | null>;
}

export interface PayrollRuns {
  created_at: Generated<Date>;
  created_by: number;
  divisor_days: Decimal;
  divisor_rule: "month_days" | "thirty" | "working_days";
  expense_id: Generated<number | null>;
  finalised_at: Generated<Date | null>;
  finalised_by: Generated<number | null>;
  id: Generated<number>;
  month: string;
  paid_method: Generated<"bank_transfer" | "card" | "cash" | "cheque" | "upi" | null>;
  paid_on: Generated<Date | null>;
  paid_reference: Generated<string | null>;
  status: Generated<"draft" | "finalised" | "paid">;
}

export interface Payslips {
  adjustments: Generated<string | null>;
  employer_total: Decimal;
  gross: Decimal;
  id: Generated<number>;
  lop_days: Generated<Decimal>;
  net_pay: Decimal;
  note: Generated<string | null>;
  paid_days: Decimal;
  public_id: string;
  run_id: number;
  slip_lines: string;
  staff_id: number;
  staff_salary_id: Generated<number | null>;
  total_deductions: Decimal;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface Permissions {
  action: string;
  description: Generated<string | null>;
  id: Generated<number>;
  module_key: string;
}

export interface PlanInstallments {
  academic_year_id: number;
  due_date: Date;
  fee_plan_id: number;
  installment_no: number;
  label: string;
}

export interface RolePermissions {
  permission_id: number;
  role_id: number;
  scope: Generated<"all" | "assigned_route" | "assigned_students" | "class" | "own_children" | "own_records" | "section" | "subject">;
}

export interface Roles {
  created_at: Generated<Date>;
  description: Generated<string | null>;
  id: Generated<number>;
  is_active: Generated<number>;
  is_system: Generated<number>;
  name: string;
  role_key: string;
  updated_at: Generated<Date>;
  workspace: Generated<"parent" | "staff" | "student">;
}

export interface RouteFees {
  academic_year_id: number;
  amount: Decimal;
  bus_route_id: number;
  due_date: Generated<Date | null>;
}

export interface RouteStops {
  bus_route_id: number;
  drop_time: Generated<string | null>;
  id: Generated<number>;
  is_active: Generated<number>;
  landmark: Generated<string | null>;
  name: string;
  pickup_time: Generated<string | null>;
  sort_order: Generated<number>;
}

export interface SalaryTemplateLines {
  component_id: number;
  template_id: number;
  value: Decimal;
}

export interface SalaryTemplates {
  created_at: Generated<Date>;
  id: Generated<number>;
  is_active: Generated<number>;
  name: string;
}

export interface SaleLines {
  amount: Decimal;
  id: Generated<number>;
  item_id: Generated<number | null>;
  label: string;
  qty: Decimal;
  sale_id: number;
  set_id: Generated<number | null>;
  unit_price: Decimal;
}

export interface Sales {
  academic_year_id: number;
  buyer_name: Generated<string | null>;
  cancel_reason: Generated<string | null>;
  cancelled_at: Generated<Date | null>;
  cancelled_by: Generated<number | null>;
  created_at: Generated<Date>;
  created_by: number;
  id: Generated<number>;
  method: "bank_transfer" | "card" | "cash" | "cheque" | "upi";
  public_id: string;
  receipt_no: string;
  reference_no: Generated<string | null>;
  sale_date: Date;
  status: Generated<"active" | "cancelled">;
  student_id: Generated<number | null>;
  total: Decimal;
}

export interface SchemaMigrations {
  applied_at: Generated<Date>;
  checksum: string;
  filename: string;
}

export interface SchemaMigrationSteps {
  checksum: string;
  filename: string;
  step: number;
}

export interface Sections {
  class_id: number;
  id: Generated<number>;
  is_active: Generated<number>;
  name: string;
}

export interface Sessions {
  created_at: Generated<Date>;
  device_label: Generated<string | null>;
  expires_at: Date;
  id: Generated<number>;
  impersonator_id: Generated<number | null>;
  ip_address: Generated<string | null>;
  last_used_at: Generated<Date | null>;
  refresh_token_hash: string;
  revoked_at: Generated<Date | null>;
  user_agent: Generated<string | null>;
  user_id: number;
}

export interface Settings {
  is_developer_only: Generated<number>;
  setting_group: string;
  setting_key: string;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
  value: string;
}

export interface SkillRatings {
  rating: "excellent" | "good" | "needs_practice";
  skill_id: number;
  student_id: number;
  term: number;
  updated_by: Generated<number | null>;
}

export interface Skills {
  academic_year_id: number;
  class_id: Generated<number | null>;
  group_name: string;
  id: Generated<number>;
  name: string;
  position: Generated<number>;
}

export interface Staff {
  address: Generated<string | null>;
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  custom_data: Generated<string | null>;
  deleted_at: Generated<Date | null>;
  department: Generated<string | null>;
  designation: Generated<string | null>;
  dob: Generated<Date | null>;
  employee_code: string;
  experience_years: Generated<Decimal | null>;
  gender: Generated<"female" | "male" | "other" | null>;
  id: Generated<number>;
  joining_date: Generated<Date | null>;
  photo_file_id: Generated<number | null>;
  public_id: string;
  qualification: Generated<string | null>;
  status: Generated<"active" | "inactive">;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
  user_id: number;
}

export interface StaffAttendance {
  accuracy_m: Generated<number | null>;
  att_date: Date;
  check_in_at: Generated<Date | null>;
  distance_m: Generated<number | null>;
  id: Generated<number>;
  source: "admin" | "leave" | "self";
  staff_id: number;
  status: "absent" | "half_day" | "leave" | "present";
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface StaffHr {
  bank_account_no: Generated<string | null>;
  bank_ifsc: Generated<string | null>;
  bank_name: Generated<string | null>;
  emergency_mobile: Generated<string | null>;
  emergency_name: Generated<string | null>;
  employment_type: Generated<"contract" | "part_time" | "permanent" | "probation" | null>;
  esi_no: Generated<string | null>;
  exit_date: Generated<Date | null>;
  exit_reason: Generated<string | null>;
  notes: Generated<string | null>;
  pan_no: Generated<string | null>;
  staff_id: number;
  uan_no: Generated<string | null>;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface StaffSalaries {
  created_at: Generated<Date>;
  created_by: number;
  effective_from: Date;
  id: Generated<number>;
  note: Generated<string | null>;
  staff_id: number;
  template_id: Generated<number | null>;
}

export interface StaffSalaryLines {
  component_id: number;
  staff_salary_id: number;
  value: Decimal;
}

export interface StockMovements {
  amount: Generated<Decimal | null>;
  balance_after: Decimal;
  created_at: Generated<Date>;
  created_by: number;
  expense_id: Generated<number | null>;
  id: Generated<number>;
  item_id: number;
  kind: "adjust" | "issue" | "purchase" | "sale" | "sale_cancel";
  move_date: Date;
  note: Generated<string | null>;
  party: Generated<string | null>;
  qty: Decimal;
  sale_id: Generated<number | null>;
}

export interface StudentAttendance {
  academic_year_id: number;
  att_date: Date;
  id: Generated<number>;
  marked_by: Generated<number | null>;
  section_id: number;
  source: Generated<"admin" | "import" | "leave" | "teacher">;
  status: "absent" | "half_day" | "late" | "leave" | "present";
  student_id: number;
  updated_at: Generated<Date>;
}

export interface StudentExits {
  bonafide_issued_on: Generated<Date | null>;
  bonafide_marked_by: Generated<number | null>;
  bonafide_number: Generated<string | null>;
  created_at: Generated<Date>;
  created_by: number;
  leaving_date: Date;
  reason: string;
  student_id: number;
  tc_issued_on: Generated<Date | null>;
  tc_marked_by: Generated<number | null>;
  tc_number: Generated<string | null>;
}

export interface StudentFeeAccounts {
  academic_year_id: number;
  bus_concession_type_id: Generated<number | null>;
  bus_discount: Generated<Decimal>;
  bus_gross: Generated<Decimal>;
  bus_route_id: Generated<number | null>;
  class_id: number;
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  fee_plan_id: number;
  has_payments: Generated<number>;
  id: Generated<number>;
  student_id: number;
  tuition_concession_type_id: Generated<number | null>;
  tuition_discount: Generated<Decimal>;
  tuition_gross: Decimal;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface Students {
  address: Generated<string | null>;
  admission_date: Generated<Date | null>;
  admission_no: string;
  blood_group: Generated<string | null>;
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  custom_data: Generated<string | null>;
  dob: Generated<Date | null>;
  family_id: number;
  first_name: string;
  gender: Generated<"female" | "male" | "other" | null>;
  id: Generated<number>;
  inactive_at: Generated<Date | null>;
  inactive_reason: Generated<string | null>;
  last_name: Generated<string | null>;
  photo_file_id: Generated<number | null>;
  public_id: string;
  status: Generated<"active" | "inactive">;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
  user_id: Generated<number | null>;
}

export interface StudentStops {
  academic_year_id: number;
  route_stop_id: number;
  student_id: number;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface Subjects {
  code: Generated<string | null>;
  id: Generated<number>;
  is_active: Generated<number>;
  name: string;
}

export interface TeacherAssignments {
  academic_year_id: number;
  id: Generated<number>;
  section_id: number;
  staff_id: number;
  subject_id: number;
}

export interface TermRemarks {
  academic_year_id: number;
  remarks: string;
  student_id: number;
  term: number;
  updated_by: Generated<number | null>;
}

export interface TimetableSlots {
  academic_year_id: number;
  bell_period_id: number;
  day_of_week: number;
  id: Generated<number>;
  section_id: number;
  subject_id: number;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface UserPermissionOverrides {
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  effect: "deny" | "grant";
  permission_id: number;
  scope: Generated<"all" | "assigned_route" | "assigned_students" | "class" | "own_children" | "own_records" | "section" | "subject" | null>;
  user_id: number;
  workspace: "parent" | "staff" | "student";
}

export interface UserRoles {
  assigned_by: Generated<number | null>;
  created_at: Generated<Date>;
  role_id: number;
  user_id: number;
  valid_from: Generated<Date | null>;
  valid_to: Generated<Date | null>;
}

export interface Users {
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  email: Generated<string | null>;
  email_verified_at: Generated<Date | null>;
  failed_login_count: Generated<number>;
  id: Generated<number>;
  is_super_admin: Generated<number>;
  last_login_at: Generated<Date | null>;
  locked_until: Generated<Date | null>;
  mobile: Generated<string | null>;
  must_change_password: Generated<number>;
  name: string;
  password_changed_at: Generated<Date | null>;
  password_hash: Generated<string | null>;
  public_id: string;
  status: Generated<"active" | "auto_disabled" | "disabled">;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface VehicleLogs {
  amount: Decimal;
  cancel_reason: Generated<string | null>;
  created_at: Generated<Date>;
  created_by: number;
  description: Generated<string | null>;
  expense_id: Generated<number | null>;
  id: Generated<number>;
  kind: "fuel" | "service";
  litres: Generated<Decimal | null>;
  log_date: Date;
  odometer: Generated<number | null>;
  public_id: string;
  status: Generated<"active" | "cancelled">;
  vehicle_id: number;
  vendor: Generated<string | null>;
}

export interface Vehicles {
  driver_staff_id: Generated<number | null>;
  helper_mobile: Generated<string | null>;
  helper_name: Generated<string | null>;
  id: Generated<number>;
  is_active: Generated<number>;
  name: Generated<string | null>;
  notes: Generated<string | null>;
  reg_no: string;
  seats: Generated<number | null>;
}

export interface DB {
  academic_year_fee_settings: AcademicYearFeeSettings;
  academic_years: AcademicYears;
  announcements: Announcements;
  attendance_days: AttendanceDays;
  audit_logs: AuditLogs;
  bell_group_classes: BellGroupClasses;
  bell_groups: BellGroups;
  bell_periods: BellPeriods;
  bus_routes: BusRoutes;
  class_exam_settings: ClassExamSettings;
  class_one_time_fees: ClassOneTimeFees;
  class_subjects: ClassSubjects;
  class_teachers: ClassTeachers;
  class_tuition_fees: ClassTuitionFees;
  classes: Classes;
  cms_albums: CmsAlbums;
  cms_events: CmsEvents;
  cms_home_sections: CmsHomeSections;
  cms_menu_items: CmsMenuItems;
  cms_pages: CmsPages;
  cms_photos: CmsPhotos;
  cms_videos: CmsVideos;
  co_areas: CoAreas;
  co_grades: CoGrades;
  concession_types: ConcessionTypes;
  contact_messages: ContactMessages;
  credential_issues: CredentialIssues;
  email_outbox: EmailOutbox;
  email_templates: EmailTemplates;
  enrollments: Enrollments;
  exam_classes: ExamClasses;
  exam_publications: ExamPublications;
  exam_schedule: ExamSchedule;
  exams: Exams;
  expense_categories: ExpenseCategories;
  expenses: Expenses;
  families: Families;
  feature_flags: FeatureFlags;
  fee_items: FeeItems;
  fee_plans: FeePlans;
  fee_reminder_log: FeeReminderLog;
  fee_waiver_items: FeeWaiverItems;
  fee_waivers: FeeWaivers;
  field_policies: FieldPolicies;
  files: Files;
  grade_bands: GradeBands;
  grade_scales: GradeScales;
  holidays: Holidays;
  import_jobs: ImportJobs;
  institution_settings: InstitutionSettings;
  inventory_items: InventoryItems;
  item_set_lines: ItemSetLines;
  item_sets: ItemSets;
  leave_requests: LeaveRequests;
  leave_types: LeaveTypes;
  login_logs: LoginLogs;
  mark_corrections: MarkCorrections;
  mark_sheets: MarkSheets;
  marks: Marks;
  notifications: Notifications;
  number_sequences: NumberSequences;
  one_time_fee_types: OneTimeFeeTypes;
  password_reset_tokens: PasswordResetTokens;
  pay_components: PayComponents;
  payment_allocations: PaymentAllocations;
  payments: Payments;
  payroll_runs: PayrollRuns;
  payslips: Payslips;
  permissions: Permissions;
  plan_installments: PlanInstallments;
  role_permissions: RolePermissions;
  roles: Roles;
  route_fees: RouteFees;
  route_stops: RouteStops;
  salary_template_lines: SalaryTemplateLines;
  salary_templates: SalaryTemplates;
  sale_lines: SaleLines;
  sales: Sales;
  schema_migration_steps: SchemaMigrationSteps;
  schema_migrations: SchemaMigrations;
  sections: Sections;
  sessions: Sessions;
  settings: Settings;
  skill_ratings: SkillRatings;
  skills: Skills;
  staff: Staff;
  staff_attendance: StaffAttendance;
  staff_hr: StaffHr;
  staff_salaries: StaffSalaries;
  staff_salary_lines: StaffSalaryLines;
  stock_movements: StockMovements;
  student_attendance: StudentAttendance;
  student_exits: StudentExits;
  student_fee_accounts: StudentFeeAccounts;
  student_stops: StudentStops;
  students: Students;
  subjects: Subjects;
  teacher_assignments: TeacherAssignments;
  term_remarks: TermRemarks;
  timetable_slots: TimetableSlots;
  user_permission_overrides: UserPermissionOverrides;
  user_roles: UserRoles;
  users: Users;
  vehicle_logs: VehicleLogs;
  vehicles: Vehicles;
}
